version: "3.9"
services:
  workspace:
    container_name: ${PROJECT_NAME:-default}-workspace
    build:
      context: ./docker/workspace
      args:
        USERNAME: vscode
        USER_GROUP_NAME: workspace
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    tty: true
    volumes:
      - ../:/home/vscode/workspace:cached
    ports:
      - 5555:5555
    command: sleep infinity
